name: main

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python (pip)
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: .github/workflows/main.yml

      - name: Install poetry
        run: |
          python3 -m pip install --upgrade poetry==2.1.1

      - name: Setup Python (poetry)
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry install

      - name: Build
        run: |
          poetry run mkdocs build --strict

      - name: Pack result
        run: |
          tar -czf site.tar.gz ./site

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: site.tar.gz

  deploy-docker:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    if: (github.repository == 'digital-blueprint/handbook' && github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Log in
        run: |
          echo "$TOKEN" | docker login ghcr.io --username "$USERNAME" --password-stdin
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.actor }}
      - name: Build image
        run: |
          docker build --tag ghcr.io/digital-blueprint/handbook:latest .
      - name: Deploy image
        run: |
          docker push ghcr.io/digital-blueprint/handbook:latest
